import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {

    in property <string> results: "";
    callback calculate(string);

    background: #313e50;
    GridLayout {
        padding: 50px;
        spacing: 25px;

        Row {
            Text {
                text: "Income:";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
                color: white;
            }
        }

        Row {
            income := LineEdit {
                placeholder-text: "Your digits...";
                horizontal-alignment: center;
                font-size: 16px;
                height: 35px;
            }
        }

        Row {
            Button {
                text: "Calculate";
                primary: true;
                height: 35px;
                clicked => {
                    calculate(income.text)
                }
            }
        }

        Row {
            VerticalBox {
                Text {
                    color: white;
                    font-size: 18px;
                    font-weight: 900;
                    text: "Calculated Allowances";
                }

                Rectangle {
                    height: 120px;
                    background: #f2f2f2;

                    Text {
                        color: black;
                        font-size: 16px;
                        font-weight: 500;
                        text: root.results;
                    }
                }
            }
        }
    }
}
